[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

; Build options
build_flags = 
    -DCORE_DEBUG_LEVEL=3
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DCONFIG_SPIRAM_CACHE_WORKAROUND
    -DUSER_SETUP_LOADED
    -include src/User_Setup.h

; Libraries
lib_deps =
    bodmer/TFT_eSPI@^2.5.43
    https://github.com/earlephilhower/ESP8266Audio.git

; === FULL iPod UI ===
build_src_filter = +<ipod_main.cpp>

; Monitor settings
monitor_speed = 115200
monitor_filters = esp32_exception_decoder

; Upload settings
upload_speed = 921600

; Partition scheme for large apps
board_build.partitions = huge_app.csv
board_build.filesystem = littlefs
